apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ServiceCfgmap}}
  namespace: {{Namespace}}
data:
  TIGO_SERVICE: '{{TIGO_SERVICE}}'
  TIGO_MOBILE_SERVICE: '{{TIGO_MOBILE_SERVICE}}'
  ELFEC_SERVICE: '{{ELFEC_SERVICE}}'
  YPFB_SERVICE: '{{YPFB_SERVICE}}'
  PEXPRESS_SERVICE: '{{PEXPRESS_SERVICE}}'
  DELAPAZ_SERVICE: '{{DELAPAZ_SERVICE}}'
  COMTECO_SERVICE: '{{COMTECO_SERVICE}}'
  COTEL_SERVICE: '{{COTEL_SERVICE}}'
  PAGO_FACIL_SERVICE: '{{PAGO_FACIL_SERVICE}}'
  MONGO_URL: '{{MONGO_URL}}'
  MONGO_DB_NAME: '{{MONGO_DB_NAME}}'
  MONGO_LOG_COLLECTION: '{{MONGO_LOG_COLLECTION}}'
  MONGO_COLLECTION: '{{MONGO_COLLECTION}}'
  MONGO_COLLECTION_ETIQUETAS_TRADUCIDAS: '{{MONGO_COLLECTION_ETIQUETAS_TRADUCIDAS}}'
